# docker-compose.yml
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mailforge
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mysql_test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mailforge_test
    ports:
      - "3307:3306"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"   # SMTP trap
      - "8025:8025"   # Web UI to view caught emails

volumes:
  mysql_data: