// Package docs Code generated by swag/swag. DO NOT EDIT
package docs

import "github.com/venosm/swag"

const docTemplate = `{
    "components": {
        "schemas": {
            "internal_modules_auth.AuthResponse": {
                "properties": {
                    "access_token": {
                        "description": "Signed RS256 JWT",
                        "type": "string"
                    },
                    "expires_in": {
                        "description": "S",
                        "type": "integer"
                    },
                    "refresh_token": {
                        "description": "Opaque UUID",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "internal_modules_auth.LoginRequest": {
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "minLength": 8,
                        "type": "string"
                    }
                },
                "required": [
                    "email",
                    "password"
                ],
                "type": "object"
            },
            "internal_modules_auth.LogoutRequest": {
                "properties": {
                    "refresh_token": {
                        "type": "string"
                    }
                },
                "required": [
                    "refresh_token"
                ],
                "type": "object"
            },
            "internal_modules_auth.RefreshRequest": {
                "properties": {
                    "refresh_token": {
                        "type": "string"
                    }
                },
                "required": [
                    "refresh_token"
                ],
                "type": "object"
            },
            "internal_modules_auth.RegisterRequest": {
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "minLength": 8,
                        "type": "string"
                    },
                    "username": {
                        "minLength": 3,
                        "type": "string"
                    }
                },
                "required": [
                    "username",
                    "email",
                    "password"
                ],
                "type": "object"
            },
            "mailForgeApi_internal_shared_response.ErrorBody": {
                "properties": {
                    "error": {
                        "$ref": "#/components/schemas/mailForgeApi_internal_shared_response.ErrorDetail"
                    },
                    "request_id": {
                        "type": "string"
                    },
                    "success": {
                        "type": "boolean"
                    }
                },
                "type": "object"
            },
            "mailForgeApi_internal_shared_response.ErrorDetail": {
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    }
                },
                "type": "object"
            }
        },
        "securitySchemes": {
            "BearerAuth": {
                "description": "Type \"Bearer\" followed by a space and the JWT access token.",
                "in": "header",
                "name": "Authorization",
                "type": "apiKey"
            }
        }
    },
    "info": {
        "contact": {},
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "openapi": "3.0.0",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates a user and returns an access/refresh token pair.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/internal_modules_auth.LoginRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_modules_auth.AuthResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/mailForgeApi_internal_shared_response.ErrorBody"
                                }
                            }
                        },
                        "description": "validation error (missing/invalid field)"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/mailForgeApi_internal_shared_response.ErrorBody"
                                }
                            }
                        },
                        "description": "invalid credentials"
                    }
                },
                "summary": "Login a user",
                "tags": [
                    "auth"
                ]
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Invalidates the given refresh token.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/internal_modules_auth.LogoutRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "204": {
                        "description": "no content"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/mailForgeApi_internal_shared_response.ErrorBody"
                                }
                            }
                        },
                        "description": "validation error (missing/invalid field)"
                    }
                },
                "summary": "Logout a user",
                "tags": [
                    "auth"
                ]
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Generates a new access token using a valid refresh token.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/internal_modules_auth.RefreshRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_modules_auth.AuthResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/mailForgeApi_internal_shared_response.ErrorBody"
                                }
                            }
                        },
                        "description": "validation error (missing/invalid field)"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/mailForgeApi_internal_shared_response.ErrorBody"
                                }
                            }
                        },
                        "description": "invalid refresh token"
                    }
                },
                "summary": "Refresh an access token",
                "tags": [
                    "auth"
                ]
            }
        },
        "/auth/register": {
            "post": {
                "description": "Creates a new user account and returns an access/refresh token pair.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/internal_modules_auth.RegisterRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/internal_modules_auth.AuthResponse"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/mailForgeApi_internal_shared_response.ErrorBody"
                                }
                            }
                        },
                        "description": "validation error (missing/invalid field)"
                    },
                    "409": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/mailForgeApi_internal_shared_response.ErrorBody"
                                }
                            }
                        },
                        "description": "email already registered"
                    }
                },
                "summary": "Register a new user",
                "tags": [
                    "auth"
                ]
            }
        }
    },
    "servers": [
        {
            "url": "{{.Scheme}}://{{.Host}}{{.BasePath}}"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:3010",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MailForge API",
	Description:      "MailForge backend API. Phase B covers authentication and identity — registration, login, token refresh, and logout.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
